#ifndef SIMPLEPLATFORMER_ENGINE_RENDERABLE_TRIANGLE_ATTRIBUTE_H
#define SIMPLEPLATFORMER_ENGINE_RENDERABLE_TRIANGLE_ATTRIBUTE_H
#include <engine/color.hpp>
struct TriangleAttribute {
  float side_length;
  Color color;
};
#endif // SIMPLEPLATFORMER_ENGINE_RENDERABLE_TRIANGLE_ATTRIBUTE_H
