#ifndef SIMPLEPLATFORMER_ENGINE_ALIGNMENT_HPP
#define SIMPLEPLATFORMER_ENGINE_ALIGNMENT_HPP
extern "C" {
#include <allegro5/allegro_font.h>
}
enum struct Alignment { ALIGN_LEFT = ALLEGRO_ALIGN_LEFT, ALIGN_RIGHT = ALLEGRO_ALIGN_RIGHT, ALIGN_CENTER = ALLEGRO_ALIGN_CENTER };
#endif // SIMPLEPLATFORMER_ENGINE_ALIGNMENT_HPP
