#ifndef SIMPLEPLATFORMER_ENGINE_EVENT_EVENT_END_CONTACT_HPP
#define SIMPLEPLATFORMER_ENGINE_EVENT_EVENT_END_CONTACT_HPP
struct EventEndContact {
  std::uint_fast64_t other_id;
};
#endif // SIMPLEPLATFORMER_ENGINE_EVENT_EVENT_END_CONTACT_HPP
