#ifndef SIMPLEPLATFORMER_ENGINE_EVENT_EVENT_BEGIN_CONTACT_HPP
#define SIMPLEPLATFORMER_ENGINE_EVENT_EVENT_BEGIN_CONTACT_HPP
struct EventBeginContact {
  std::uint_fast64_t other_id;
};
#endif // SIMPLEPLATFORMER_ENGINE_EVENT_EVENT_BEGIN_CONTACT_HPP
