#ifndef SIMPLEPLATFORMER_ENGINE_EVENT_EVENT_CONTACT_HPP
#define SIMPLEPLATFORMER_ENGINE_EVENT_EVENT_CONTACT_HPP
#include <cstdint>
struct EventContact {
  std::uint_fast64_t other_id;
};
#endif // SIMPLEPLATFORMER_ENGINE_EVENT_EVENT_CONTACT_HPP
