#ifndef SIMPLEPLATFORMER_ENGINE_EVENT_KEYCODE_HPP
#define SIMPLEPLATFORMER_ENGINE_EVENT_KEYCODE_HPP
extern "C" {
#include <allegro5/allegro.h>
}
enum struct KeyCode {
  // Alphabets
  A = ALLEGRO_KEY_A,
  B = ALLEGRO_KEY_B,
  C = ALLEGRO_KEY_C,
  D = ALLEGRO_KEY_D,
  E = ALLEGRO_KEY_E,
  F = ALLEGRO_KEY_F,
  G = ALLEGRO_KEY_G,
  H = ALLEGRO_KEY_H,
  I = ALLEGRO_KEY_I,
  J = ALLEGRO_KEY_J,
  K = ALLEGRO_KEY_K,
  L = ALLEGRO_KEY_L,
  M = ALLEGRO_KEY_M,
  N = ALLEGRO_KEY_N,
  O = ALLEGRO_KEY_O,
  P = ALLEGRO_KEY_P,
  Q = ALLEGRO_KEY_Q,
  R = ALLEGRO_KEY_R,
  S = ALLEGRO_KEY_S,
  T = ALLEGRO_KEY_T,
  U = ALLEGRO_KEY_U,
  V = ALLEGRO_KEY_V,
  W = ALLEGRO_KEY_W,
  X = ALLEGRO_KEY_X,
  Y = ALLEGRO_KEY_Y,
  Z = ALLEGRO_KEY_Z,

  // Numbers
  ZERO = ALLEGRO_KEY_0,
  ONE = ALLEGRO_KEY_1,
  TWO = ALLEGRO_KEY_2,
  THREE = ALLEGRO_KEY_3,
  FOUR = ALLEGRO_KEY_4,
  FIVE = ALLEGRO_KEY_5,
  SIX = ALLEGRO_KEY_6,
  SEVEN = ALLEGRO_KEY_7,
  EIGHT = ALLEGRO_KEY_8,
  NINE = ALLEGRO_KEY_9,

  // Arrows
  LEFT = ALLEGRO_KEY_LEFT,
  RIGHT = ALLEGRO_KEY_RIGHT,
  UP = ALLEGRO_KEY_UP,
  DOWN = ALLEGRO_KEY_DOWN
};
#endif // SIMPLEPLATFORMER_ENGINE_EVENT_KEYCODE_HPP
